### ISSUE TITLE
Scala 3 Support

### ISSUE THREAD

**Issue by etspaceman** [wolfendale/scalacheck-gen-regexp#10]
Hey there - 

Looks like Scalacheck has Scala3 support. It would be great if this repository also had the same.

**Comment by wolfendale** [comment]
Great idea, I haven't done much with Scala 3 yet but would happily take a look at a PR. Looks like parser-combinators has a release for 3 too so shouldn't be any problems with dependencies.

**Comment by wolfendale** [comment]
I just had a look into this, looks like there's not a common version between dependencies that we can use yet. Parser combinators is only released for `3.0.0-RC3`. Once this is released a 3 I'll update and do a new cross build.

**Comment by sergewar** [comment]
Scala 3 already released. Could you please update this library for Scala 3?

**Comment by wolfendale** [comment]
Hey, sorry about the delay on this. I've just pushed version 1.0.0 which should have Scala 3 support
