### ISSUE TITLE
cross build with scala 3.2

### ISSUE THREAD

**Issue by frikit** [wolfendale/scalacheck-gen-regexp#12]
https://www.scala-lang.org/blog/2022/09/05/scala-3.2.0-released.html

Would be good to have this cross build for scala 3.2 as well as 3.1 as you already have in the project

**Comment by wolfendale** [comment]
I've done this and released version 1.1.0

Scala 3 doesn't work in the same way as Scala 2, there aren't separately cross compiled bins for different minor versions. 1.1.0 will be built with 3.2 (until a new version of course!)
