### ISSUE TITLE
Scalacheck version confusion 

### ISSUE THREAD

**Issue by frikit** [wolfendale/scalacheck-gen-regexp#13]
Hey,

You have scalacheck version here https://github.com/wolfendale/scalacheck-gen-regexp/blob/master/build.sbt#L19 set to 1.17
and then you have here https://github.com/wolfendale/scalacheck-gen-regexp/blob/master/build.sbt#L23 set to 1.16
in most of the project I've seen so far most of the people instead of adding one library which is `scalacheck-gen-regexp` to pull all transitive dependencies to make it work we are adding all libraries like here https://github.com/hmrc/trusts-non-repudiation-stub/blob/c4405a6e8946a68a71a85f7e06e92203c4cd80b5/project/AppDependencies.scala and sometimes I've seen adding even scalacheck itself so it is creating confusion with scalacheck version.

Before you say that is test deps :D What I emant my suggestion to be is to add scalatestplus scalacheck as main dep in the project and everyone can add your library and everything will be pulled as transitive dependency.

PS:  the same for scalatest

**Comment by wolfendale** [comment]
Hey, I don't think I agree with this. Although it may mean that people can add only this dependency, really it shouldn't be what dictates the version of other dependencies that you use. Especially, not things like scalatest. 

For example, people may use other test libraries with scalacheck and scalacheck-gen-regexp. If we brought in scalatest / scalatestplus then people using Specs2 would get those dependencies for no reason, it may even cause issues!

Overall, I just don't think the benefit of this outweighs the negatives.
