### ISSUE TITLE
Artifact seems to be missing

### ISSUE THREAD

**Issue by etspaceman** [wolfendale/scalacheck-gen-regexp#8]
Looks like the artifact for this repository is gone:

```
[error] sbt.librarymanagement.ResolveException: Error downloading wolfendale:scalacheck-gen-regexp_2.13:0.1.2
[error]   Not found
[error]   Not found
[error]   not found: /home/runner/.ivy2/localwolfendale/scalacheck-gen-regexp_2.13/0.1.2/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/wolfendale/scalacheck-gen-regexp_2.13/0.1.2/scalacheck-gen-regexp_2.13-0.1.2.pom
[error]   forbidden: https://dl.bintray.com/wolfendale/maven/wolfendale/scalacheck-gen-regexp_2.13/0.1.2/scalacheck-gen-regexp_2.13-0.1.2.pom
```

Has this been transitioned to another area? 

I'm happy to fork this and host it under my mavencentral. Not sure if this is getting updates anymore 😕

**Comment by wolfendale** [comment]
@etspaceman I think this might be an issue with jfrog sunsetting bintray related things. I believe they still intend to host jcenter permanently as a read only store and this should be available there. Does this work if you remove the specific resolver for my bintray repo and add one for jcenter?

**Comment by etspaceman** [comment]
@wolfendale it does not work:

https://github.com/etspaceman/scalacheck-faker/pull/173/checks?check_run_id=2511186943

**Comment by wolfendale** [comment]
@etspaceman that error looks like it's for another library? `scalac-scoverage-runtime`?

**Comment by wolfendale** [comment]
@etspaceman I've gone through the process to get this onto Sonatype OSSRH, it's published but I'm waiting for the sync to maven central. Will keep an eye on it and at you when I notice it's there. It's published under a new version + groupId so you'll have to update that in your project but the code is identical.

I'm updating the README now to reflect the updated groupId and removed the resolver from the example.

Thanks for kicking me into doing this, it was sheer laziness that I'd never gotten around to publishing to maven central :)

**Comment by etspaceman** [comment]
Awesome! Thanks!

**Comment by wolfendale** [comment]
@etspaceman Looks like it's [synced to the repo](https://repo1.maven.org/maven2/io/github/wolfendale/) now although it doesn't appear in the search quite yet (apparently should show up in the next couple of hours) so I'm going to close this issue.

Thanks again
